// Code generated by "stringer -type=ClientName -output=http_client_name_string.go"; DO NOT EDIT.
// 此文件由 stringer 工具自动生成,不要手动编辑
// stringer 是 Go 官方工具,用于为枚举类型自动生成 String() 方法
// 重新生成命令: go generate ./...

package client

import "strconv"

// 编译时检查,确保常量值没有改变
// 如果常量定义发生变化,这里会产生编译错误,提示需要重新生成代码
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Client-0]  // 确保 Client 的值为 0
}

// _ClientName_name 包含所有客户端名称的连续字符串
// 这是一种优化技术,将所有名称存储在一个字符串中,减少内存分配
const _ClientName_name = "Client"

// _ClientName_index 索引数组,标记每个名称在 _ClientName_name 中的起始位置
// 索引数组的长度比枚举值数量多1,最后一个元素表示字符串的总长度
var _ClientName_index = [...]uint8{0, 6}

// String 将 ClientName 枚举值转换为字符串
// 这是 fmt.Stringer 接口的实现
//
// 返回:
//   string: 客户端名称字符串,如 "Client"
//           如果值无效,返回 "ClientName(n)" 格式
//
// 示例:
//   name := Client
//   fmt.Println(name.String())  // 输出: Client
func (i ClientName) String() string {
	// 检查枚举值是否在有效范围内
	if i < 0 || i >= ClientName(len(_ClientName_index)-1) {
		// 无效值返回 "ClientName(数字)" 格式
		return "ClientName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	// 通过索引从 _ClientName_name 中提取对应的子字符串
	return _ClientName_name[_ClientName_index[i]:_ClientName_index[i+1]]
}
